const translations = {
    ru: {
      'nav.home': 'Главная',
      'nav.services': 'Услуги и продукция',
      'nav.training': 'Обучение и материалы',
      'nav.about': 'О нас',
      'nav.contact': 'Связаться',
      'hero.title': 'Услуги по ремонту и обслуживанию электродвигателей',
      'service.title': 'Увеличьте срок службы вашего двигателя',
      'service.description': 'Наш спектр услуг по обслуживанию двигателей призван обеспечить бесперебойную, надежную и эффективную работу ваших электродвигателей. От ремонта и капитального ремонта до индивидуальных решений для различных типов двигателей.',
      'service.cta': 'Доверьте нам решение ваших проблем с двигателем.',
      'reliability.title': 'Повышение надежности',
      'reliability.description': 'Наши процедуры ремонта и капитального ремонта двигателей в сочетании с точными методами перемотки двигателей восстанавливают ваши двигатели до пикового состояния, повышая надежность и сводя к минимуму риск непредвиденных простоев. Благодаря испытаниям и диагностике двигателей мы выявляем потенциальные проблемы на ранних этапах и обеспечиваем максимальную надежность.',
      'reliability.cta': 'Доверьтесь нам, чтобы ваши двигатели работали плавно и надежно на каждом этапе пути.',
      'extend.title': 'Доверьте нам продление срока службы вашего двигателя.',
      'extend.button': 'Связаться',
      'services.hero': 'Услуги и продукция',
      'services.repair.title': 'Ремонт двигателей',
      'services.repair.desc': 'Профессиональный ремонт электродвигателей любой сложности с гарантией качества.',
      'services.maintenance.title': 'Обслуживание',
      'services.maintenance.desc': 'Регулярное техническое обслуживание для продления срока службы оборудования.',
      'services.diagnostics.title': 'Диагностика',
      'services.diagnostics.desc': 'Современная диагностика с использованием профессионального оборудования.',
      'services.rewinding.title': 'Перемотка',
      'services.rewinding.desc': 'Качественная перемотка статоров и роторов электродвигателей.',
      'training.hero': 'Обучение и материалы',
      'training.courses.title': 'Обучающие курсы',
      'training.courses.desc': 'Мы предлагаем профессиональное обучение по ремонту и обслуживанию электродвигателей для специалистов различного уровня.',
      'training.materials.title': 'Технические материалы',
      'training.materials.desc': 'База знаний, руководства и инструкции по эксплуатации электродвигателей.',
      'about.hero': 'О нас',
      'about.company.title': 'О компании',
      'about.company.desc': 'EMR — ведущая компания в области ремонта и обслуживания электродвигателей с многолетним опытом работы.',
      'about.team.title': 'Наша команда',
      'about.team.desc': 'Команда высококвалифицированных специалистов с большим опытом в сфере электротехники.',
      'contact.title': 'Напишите нам',
      'contact.name': 'Фамилия и Имя',
      'contact.company': 'Название Компании',
      'contact.phone': 'Тел. Номер',
      'contact.email': 'Почта',
      'contact.message': 'Сообщение',
      'contact.submit': 'Подтвердить',
      'contact.info_title': 'Контактная информация',
      'contact.address': '📍 Адрес: Улица Орынгали Смагулов, 13',
  
      'services.hero.title': 'Услуги и продукция',
      'services.hero.subtitle': 'Комплексный ремонт и обслуживание электродвигателей с гарантией качества',
      'services.hero.button': 'Запросить расчёт',
      'services.services.title': 'Наши услуги',
      'services.service1.title': 'Ремонт электродвигателей',
      'services.service1.desc': 'Капитальный и текущий ремонт асинхронных и синхронных двигателей любой сложности.',
      'services.service1.item1': 'Замена подшипниковых узлов',
      'services.service1.item2': 'Ремонт корпуса и вала',
      'services.service1.item3': 'Восстановление геометрии',
      'services.service2.title': 'Перемотка обмоток',
      'services.service2.desc': 'Профессиональная перемотка статора и ротора с использованием качественных материалов.',
      'services.service2.item1': 'Полная замена обмоток',
      'services.service2.item2': 'Пропитка изоляции',
      'services.service2.item3': 'Контроль сопротивления',
      'services.service3.title': 'Диагностика и испытания',
      'services.service3.desc': 'Комплексная диагностика с применением современного измерительного оборудования.',
      'services.service3.item1': 'Вибродиагностика',
      'services.service3.item2': 'Межвитковые испытания',
      'services.service3.item3': 'Измерение сопротивления изоляции',
      'services.service4.title': 'Техническое обслуживание',
      'services.service4.desc': 'Регулярное ТО для предотвращения аварийных ситуаций и продления срока службы.',
      'services.service4.item1': 'Плановые осмотры',
      'services.service4.item2': 'Смазка подшипников',
      'services.service4.item3': 'Проверка креплений',
      'services.service5.title': 'Балансировка ротора',
      'services.service5.desc': 'Точная динамическая балансировка для устранения вибраций и шума.',
      'services.service5.item1': 'Балансировка на стенде',
      'services.service5.item2': 'Устранение биений',
      'services.service5.item3': 'Центровка валов',
      'services.service6.title': 'Модернизация и апгрейд',
      'services.service6.desc': 'Улучшение характеристик двигателя и внедрение современных технологий.',
      'services.service6.item1': 'Установка датчиков',
      'services.service6.item2': 'Повышение класса изоляции',
      'services.service6.item3': 'Оптимизация охлаждения',
  
      'services.products.title': 'Продукция',
      'services.product1.title': 'Подшипники и ремкомплекты',
      'services.product1.desc': 'Качественные подшипники от ведущих мировых производителей для всех типов двигателей.',
      'services.product1.item1': 'Шариковые подшипники',
      'services.product1.item2': 'Роликовые подшипники',
      'services.product1.item3': 'Сальники и уплотнения',
      'services.product2.title': 'Изоляционные материалы и лаки',
      'services.product2.desc': 'Термостойкие изоляционные материалы класса F/H для надёжной защиты обмоток.',
      'services.product2.item1': 'Слюдопластовая изоляция',
      'services.product2.item2': 'Пропиточные лаки',
      'services.product2.item3': 'Электротехнический картон',
      'services.product3.title': 'Запчасти и комплектующие',
      'services.product3.desc': 'Широкий ассортимент оригинальных и совместимых запчастей для электродвигателей.',
      'services.product3.item1': 'Вентиляторы охлаждения',
      'services.product3.item2': 'Клеммные коробки',
      'services.product3.item3': 'Щёткодержатели',
  
      'services.specs.title': 'Технические возможности',
      'services.specs.note': '* Примерные значения — уточняются под конкретный проект',
      'services.specs.power.value': '0.37–500 кВт',
      'services.specs.power.label': 'Мощность',
      'services.specs.voltage.value': 'до 6.6 кВ',
      'services.specs.voltage.label': 'Напряжение',
      'services.specs.insulation.value': 'F / H',
      'services.specs.insulation.label': 'Класс изоляции',
      'services.specs.balancing.value': 'ISO 1940-1',
      'services.specs.balancing.label': 'Балансировка',
      'services.specs.testing.value': '5 видов',
      'services.specs.testing.label': 'Испытания',
      'services.specs.warranty.value': 'до 1 мес.',
      'services.specs.warranty.label': 'Гарантия',
  
      'services.why.title': 'Почему выбирают EMS',
      'services.why1.title': 'Оптимальные сроки',
      'services.why1.desc': 'Чёткое планирование работ и соблюдение договорных сроков выполнения заказа.',
      'services.why2.title': 'Контроль качества',
      'services.why2.desc': 'Многоступенчатая проверка на каждом этапе ремонта и итоговые испытания.',
      'services.why3.title': 'Договор и документы',
      'services.why3.desc': 'Официальное оформление, полный пакет документов, акты выполненных работ.',
      'services.why4.title': 'Гарантийное обслуживание',
      'services.why4.desc': 'Гарантия на все виды работ с возможностью постгарантийного обслуживания.',

      'modal.title': 'Связаться с EMS',
      'modal.subtitle': 'Выберите удобный способ',
      'modal.call': '📞 Позвонить: +7 (775) 552-44-14',
      'modal.whatsapp': '💬 WhatsApp',

      'training.hero.title': 'Обучение и материалы',
      'training.hero.subtitle': 'Профессиональные обучающие материалы и видеоинструкции по ремонту электродвигателей',
      'training.hero.button': 'Задайте свой вопрос',
      'training.videos.title': 'Обучающие видео',
      'training.videos.v1.title': 'Диагностика электродвигателей',
      'training.videos.v2.title': 'Перемотка обмоток статора',
      'training.videos.v3.title': 'Балансировка и центровка',
      'training.materials.m1.title': 'Техническая документация',
      'training.materials.m1.desc': 'Руководства по эксплуатации, схемы подключения и спецификации для различных типов электродвигателей',
      'training.materials.m2.title': 'Методические пособия',
      'training.materials.m2.desc': 'Пошаговые инструкции по ремонту, перемотке и диагностике электродвигателей с иллюстрациями',
      'training.materials.m3.title': 'Стандарты и нормы',
      'training.materials.m3.desc': 'ГОСТ, ISO и другие нормативные документы по электрооборудованию и технике безопасности',

      'about.hero.title': 'О нас',
      'about.hero.subtitle': 'Профессиональный ремонт и обслуживание электродвигателей с 2019 года',

      'about.stats.years': 'лет опыта',
      'about.stats.motors': 'двигателей в год',
      'about.stats.warranty': 'месяц гарантии',

      'about.why.title': 'Почему выбирают нас',
      'about.why.card1.title': 'Профессионализм',
      'about.why.card1.desc': 'Квалифицированные специалисты с многолетним опытом работы и регулярным повышением квалификации',
      'about.why.card2.title': 'Современное оборудование',
      'about.why.card2.desc': 'Используем новейшие диагностические приборы и ремонтное оборудование ведущих производителей',
      'about.why.card3.title': 'Гарантия качества',
      'about.why.card3.desc': 'Предоставляем официальную гарантию на все виды работ с полным пакетом документов',
      'about.why.card4.title': 'Соблюдение сроков',
      'about.why.card4.desc': 'Чётко планируем работы и выполняем заказы в согласованные сроки без задержек',

      'about.process.title': 'Как мы работаем',
      'about.process.step1.title': 'Приём заявки',
      'about.process.step1.desc': 'Вы связываетесь с нами по телефону или через форму на сайте, описываете проблему',
      'about.process.step2.title': 'Диагностика',
      'about.process.step2.desc': 'Проводим комплексную диагностику двигателя на профессиональном оборудовании',
      'about.process.step3.title': 'Согласование',
      'about.process.step3.desc': 'Составляем смету работ, согласовываем объём и сроки, заключаем договор',
      'about.process.step4.title': 'Ремонт',
      'about.process.step4.desc': 'Выполняем ремонтные работы с использованием качественных материалов и запчастей',
      'about.process.step5.title': 'Сдача объекта',
      'about.process.step5.desc': 'Проводим финальные испытания, оформляем документы и передаём двигатель заказчику',

      'about.faq.title': 'Часто задаваемые вопросы',
      'about.faq.q1.question': 'Сколько времени занимает диагностика?',
      'about.faq.q1.answer': 'Предварительная диагностика занимает от 1 до 3 часов в зависимости от типа и мощности двигателя. Результаты и рекомендации предоставляются сразу после завершения.',
      'about.faq.q2.question': 'Предоставляете ли вы гарантию на работы?',
      'about.faq.q2.answer': 'Да, мы предоставляем официальную гарантию на все виды работ сроком до 1 месяца. Гарантия оформляется документально в договоре.',
      'about.faq.q3.question': 'Какие типы двигателей вы ремонтируете?',
      'about.faq.q3.answer': 'Мы работаем с асинхронными, синхронными двигателями, двигателями постоянного тока и другими типами электродвигателей разных производителей.',
      'about.faq.q4.question': 'Нужны ли фото или видео для предварительной оценки?',
      'about.faq.q4.answer': 'Фото шильдика (табличка с данными) и общего вида двигателя помогут нам дать более точную предварительную оценку стоимости и сроков ремонта.',
      'about.faq.q5.question': 'Как узнать стоимость ремонта?',
      'about.faq.q5.answer': 'Точную стоимость мы сможем назвать только после диагностики. Предварительную оценку можем дать по телефону или по фото/данным двигателя.',
      'about.faq.q6.question': 'Как быстро можно выполнить ремонт?',
      'about.faq.q6.answer': 'Срок зависит от сложности работ: текущий ремонт — 3–5 дней, капитальный — 7–14 дней, перемотка — 10–21 день. Срочный ремонт — по согласованию.',

      'about.cta.title': 'Готовы начать работу?',
      'about.cta.subtitle': 'Свяжитесь с нами для консультации и расчёта стоимости',
      'about.cta.button': 'Связаться с нами',
    },

    en: {
      'nav.home': 'Home',
      'nav.services': 'Services & Products',
      'nav.training': 'Training & Materials',
      'nav.about': 'About Us',
      'nav.contact': 'Contact',
      'hero.title': 'Electric Motor Repair and Maintenance Services',
      'service.title': 'Extend the Life of Your Engine',
      'service.description': 'Our range of engine maintenance services is designed to ensure smooth, reliable and efficient operation of your electric motors. From repair and overhaul to customized solutions for various types of engines.',
      'service.cta': 'Trust us to solve your engine problems.',
      'reliability.title': 'Increasing Reliability',
      'reliability.description': 'Our engine repair and overhaul procedures combined with precise engine rewinding techniques restore your engines to peak condition, increasing reliability and minimizing the risk of unforeseen downtime. Through engine testing and diagnostics, we identify potential problems early and ensure maximum reliability.',
      'reliability.cta': 'Trust us to keep your engines running smoothly and reliably every step of the way.',
      'extend.title': 'Trust us to extend the life of your engine.',
      'extend.button': 'Contact',
      'services.hero': 'Services & Products',
      'services.repair.title': 'Motor Repair',
      'services.repair.desc': 'Professional repair of electric motors of any complexity with quality guarantee.',
      'services.maintenance.title': 'Maintenance',
      'services.maintenance.desc': 'Regular maintenance to extend the life of the equipment.',
      'services.diagnostics.title': 'Diagnostics',
      'services.diagnostics.desc': 'Modern diagnostics using professional equipment.',
      'services.rewinding.title': 'Rewinding',
      'services.rewinding.desc': 'Quality rewinding of stators and rotors of electric motors.',
      'training.hero': 'Training & Materials',
      'training.courses.title': 'Training Courses',
      'training.courses.desc': 'We offer professional training in repair and maintenance of electric motors for specialists of various levels.',
      'training.materials.title': 'Technical Materials',
      'training.materials.desc': 'Knowledge base, manuals and instructions for operation of electric motors.',
      'about.hero': 'About Us',
      'about.company.title': 'About the Company',
      'about.company.desc': 'EMR is a leading company in the field of repair and maintenance of electric motors with many years of experience.',
      'about.team.title': 'Our Team',
      'about.team.desc': 'A team of highly qualified specialists with extensive experience in the field of electrical engineering.',
      'contact.title': 'Contact Us',
      'contact.name': 'First and Last name',
      'contact.company': 'Company Name',
      'contact.phone': 'Phone Number',
      'contact.email': 'Email',
      'contact.message': 'Message',
      'contact.submit': 'Submit',
      'contact.info_title': 'Contact Information',
      'contact.address': '📍 Address: Oryngali Smagulov Street, 13',
  
      'services.hero.title': 'Services & Products',
      'services.hero.subtitle': 'Comprehensive electric motor repair and maintenance with quality guarantee',
      'services.hero.button': 'Request a quote',
      'services.services.title': 'Our Services',
      'services.service1.title': 'Electric Motor Repair',
      'services.service1.desc': 'Major and routine repair of induction and synchronous motors of any complexity.',
      'services.service1.item1': 'Bearing unit replacement',
      'services.service1.item2': 'Housing and shaft repair',
      'services.service1.item3': 'Geometry restoration',
      'services.service2.title': 'Winding Rewinding',
      'services.service2.desc': 'Professional stator and rotor rewinding using high-quality materials.',
      'services.service2.item1': 'Complete winding replacement',
      'services.service2.item2': 'Insulation impregnation',
      'services.service2.item3': 'Resistance control',
      'services.service3.title': 'Diagnostics & Testing',
      'services.service3.desc': 'Comprehensive diagnostics using modern measurement equipment.',
      'services.service3.item1': 'Vibration diagnostics',
      'services.service3.item2': 'Surge (turn-to-turn) testing',
      'services.service3.item3': 'Insulation resistance measurement',
      'services.service4.title': 'Preventive Maintenance',
      'services.service4.desc': 'Regular maintenance to prevent failures and extend service life.',
      'services.service4.item1': 'Scheduled inspections',
      'services.service4.item2': 'Bearing lubrication',
      'services.service4.item3': 'Fastener check',
      'services.service5.title': 'Rotor Balancing',
      'services.service5.desc': 'Accurate dynamic balancing to eliminate vibration and noise.',
      'services.service5.item1': 'Bench balancing',
      'services.service5.item2': 'Runout correction',
      'services.service5.item3': 'Shaft alignment',
      'services.service6.title': 'Modernization & Upgrade',
      'services.service6.desc': 'Improving motor performance and implementing modern technologies.',
      'services.service6.item1': 'Sensor installation',
      'services.service6.item2': 'Higher insulation class upgrade',
      'services.service6.item3': 'Cooling optimization',
  
      'services.products.title': 'Products',
      'services.product1.title': 'Bearings & Repair Kits',
      'services.product1.desc': 'Quality bearings from leading global manufacturers for all motor types.',
      'services.product1.item1': 'Ball bearings',
      'services.product1.item2': 'Roller bearings',
      'services.product1.item3': 'Seals and gaskets',
      'services.product2.title': 'Insulation Materials & Varnishes',
      'services.product2.desc': 'Heat-resistant Class F/H insulation materials for reliable winding protection.',
      'services.product2.item1': 'Mica-based insulation',
      'services.product2.item2': 'Impregnation varnishes',
      'services.product2.item3': 'Electrical insulation board',
      'services.product3.title': 'Spare Parts & Components',
      'services.product3.desc': 'Wide range of original and compatible electric motor parts and components.',
      'services.product3.item1': 'Cooling fans',
      'services.product3.item2': 'Terminal boxes',
      'services.product3.item3': 'Brush holders',
  
      'services.specs.title': 'Technical Capabilities',
      'services.specs.note': '* Approximate values — уточняются under specific project',
      'services.specs.power.value': '0.37–500 kW',
      'services.specs.power.label': 'Power',
      'services.specs.voltage.value': 'up to 6.6 kV',
      'services.specs.voltage.label': 'Voltage',
      'services.specs.insulation.value': 'F / H',
      'services.specs.insulation.label': 'Insulation Class',
      'services.specs.balancing.value': 'ISO 1940-1',
      'services.specs.balancing.label': 'Balancing',
      'services.specs.testing.value': '5 types',
      'services.specs.testing.label': 'Testing',
      'services.specs.warranty.value': 'up to 1 mo.',
      'services.specs.warranty.label': 'Warranty',
  
      'services.why.title': 'Why Choose EMS',
      'services.why1.title': 'On-time Delivery',
      'services.why1.desc': 'Clear planning and meeting agreed deadlines for every order.',
      'services.why2.title': 'Quality Control',
      'services.why2.desc': 'Multi-stage checks at every step and final acceptance tests.',
      'services.why3.title': 'Contract & Documents',
      'services.why3.desc': 'Official paperwork, full document package, completion certificates.',
      'services.why4.title': 'Warranty Service',
      'services.why4.desc': 'Warranty for all services with optional post-warranty support.',

      'modal.title': 'Contact EMS',
      'modal.subtitle': 'Choose a convenient option',
      'modal.call': '📞 Call: +7 (775) 552-44-14',
      'modal.whatsapp': '💬 WhatsApp',

      'training.hero.title': 'Training & Materials',
      'training.hero.subtitle': 'Professional training resources and video guides for electric motor repair',
      'training.hero.button': 'Ask a question',
      'training.videos.title': 'Training Videos',
      'training.videos.v1.title': 'Motor diagnostics',
      'training.videos.v2.title': 'Stator rewinding',
      'training.videos.v3.title': 'Balancing and alignment',
      'training.materials.m1.title': 'Technical Documentation',
      'training.materials.m1.desc': 'User manuals, wiring diagrams, and specifications for various motor types',
      'training.materials.m2.title': 'Methodical Guides',
      'training.materials.m2.desc': 'Step-by-step repair, rewinding, and diagnostics instructions with illustrations',
      'training.materials.m3.title': 'Standards & Regulations',
      'training.materials.m3.desc': 'GOST, ISO and other safety and electrical equipment standards',

      'about.hero.title': 'About Us',
      'about.hero.subtitle': 'Professional electric motor repair and maintenance since 2019',

      'about.stats.years': 'years of experience',
      'about.stats.motors': 'motors per year',
      'about.stats.warranty': 'month warranty',
      
      'about.why.title': 'Why Choose Us',
      'about.why.card1.title': 'Professionalism',
      'about.why.card1.desc': 'Qualified specialists with years of experience and regular training',
      'about.why.card2.title': 'Modern Equipment',
      'about.why.card2.desc': 'We use up-to-date diagnostic and repair equipment',
      'about.why.card3.title': 'Quality Guarantee',
      'about.why.card3.desc': 'Official warranty for all work with full documentation',
      'about.why.card4.title': 'On-Time Delivery',
      'about.why.card4.desc': 'We plan tasks clearly and meet agreed deadlines',

      'about.process.title': 'How We Work',
      'about.process.step1.title': 'Request Intake',
      'about.process.step1.desc': 'You contact us by phone or via the website and describe the issue',
      'about.process.step2.title': 'Diagnostics',
      'about.process.step2.desc': 'We run comprehensive diagnostics using professional equipment',
      'about.process.step3.title': 'Agreement',
      'about.process.step3.desc': 'We prepare an estimate, agree on scope and timeline, and sign a contract',
      'about.process.step4.title': 'Repair',
      'about.process.step4.desc': 'We perform repairs using quality materials and spare parts',
      'about.process.step5.title': 'Delivery',
      'about.process.step5.desc': 'Final testing, documentation, and handover to the customer',

      'about.faq.title': 'Frequently Asked Questions',
      'about.faq.q1.question': 'How long does diagnostics take?',
      'about.faq.q1.answer': 'Preliminary diagnostics takes 1–3 hours depending on motor type and power. Results and recommendations are provided right after.',
      'about.faq.q2.question': 'Do you provide a warranty?',
      'about.faq.q2.answer': 'Yes. We provide an official warranty for up to 1 month. It is documented in the agreement.',
      'about.faq.q3.question': 'What motor types do you repair?',
      'about.faq.q3.answer': 'We work with induction, synchronous, DC motors and other types from various manufacturers.',
      'about.faq.q4.question': 'Do you need photos or videos for a preliminary estimate?',
      'about.faq.q4.answer': 'A photo of the nameplate and the motor’s overall condition helps us estimate cost and timeline more accurately.',
      'about.faq.q5.question': 'How can I know the repair cost?',
      'about.faq.q5.answer': 'Exact cost is confirmed after diagnostics. A preliminary estimate is possible by phone or using photos/data.',
      'about.faq.q6.question': 'How fast can you complete the repair?',
      'about.faq.q6.answer': 'Timing depends on complexity: minor repair 3–5 days, major 7–14 days, rewinding 10–21 days. Rush service is possible by agreement.',

      'about.cta.title': 'Ready to get started?',
      'about.cta.subtitle': 'Contact us for consultation and a cost estimate',
      'about.cta.button': 'Contact us',
      
    },

    kk: {
      'nav.home':'Басты бет',
      'nav.services':'Қызметтер мен өнімдер',
      'nav.training':'Оқыту және материалдар',
      'nav.about':'Біз туралы',
      'nav.contact':'Байланыс',
      'hero.title':'Электр қозғалтқыштарын жөндеу және техникалық қызмет көрсету қызметтері',
      'service.title':'Қозғалтқыштың қызмет ету мерзімін ұзарту',
      'service.description':'Қозғалтқыштарға қызмет көрсету бойынша біздің қызметтеріміз электр қозғалтқыштарының үзіліссіз, сенімді және тиімді жұмысын қамтамасыз етуге бағытталған. Жөндеу мен күрделі жөндеуден бастап, әртүрлі қозғалтқыш түрлеріне арналған жеке шешімдерге дейін.',
      'service.cta':'Қозғалтқыш мәселелерін шешуді бізге сеніп тапсырыңыз.',
      'reliability.title':'Сенімділікті арттыру',
      'reliability.description':'Қозғалтқыштарды жөндеу және күрделі жөндеу әдістеріміз қозғалтқыштарды ең жоғары өнімділікке жеткізіп, сенімділікті арттырады және күтпеген ақаулардың алдын алады. Диагностика мен сынақтар арқылы біз ақауларды ерте анықтап, максималды жұмыс сенімділігін қамтамасыз етеміз.',
      'reliability.cta':'Біздің көмегімізбен қозғалтқыштарыңыз әрқашан тұрақты және сенімді жұмыс істейді.',
      'extend.title':'Қозғалтқыштың қызмет мерзімін ұзартуды бізге сеніп тапсырыңыз.',
      'extend.button':'Байланысу',
      'services.hero':'Қызметтер мен өнімдер',
      'services.repair.title':'Қозғалтқыштарды жөндеу',
      'services.repair.desc':'Кез келген күрделіктегі электр қозғалтқыштарын кәсіби жөндеу және сапа кепілдігі.',
      'services.maintenance.title':'Техникалық қызмет көрсету',
      'services.maintenance.desc':'Жабдықтың қызмет ету мерзімін ұзарту үшін тұрақты техникалық қызмет көрсету.',
      'services.diagnostics.title':'Диагностика',
      'services.diagnostics.desc':'Кәсіби құрал-жабдықтарды пайдаланып заманауи диагностика.',
      'services.rewinding.title':'Қайта орау',
      'services.rewinding.desc':'Электр қозғалтқыштарының статорлары мен роторларын сапалы қайта орау.',
      'training.hero':'Оқыту және материалдар',
      'training.courses.title':'Оқу курстары',
      'training.courses.desc':'Біз әртүрлі деңгейдегі мамандар үшін электр қозғалтқыштарын жөндеу және қызмет көрсету бойынша кәсіби оқытуды ұсынамыз.',
      'training.materials.title':'Техникалық материалдар',
      'training.materials.desc':'Электр қозғалтқыштарын пайдалану бойынша білім базасы, нұсқаулықтар және құжаттар.',
      'about.hero':'Біз туралы',
      'about.company.title':'Компания туралы',
      'about.company.desc':'EMR — электр қозғалтқыштарын жөндеу және техникалық қызмет көрсету саласындағы жетекші компания. Көп жылдық тәжірибесі бар.',
      'about.team.title':'Біздің команда',
      'about.team.desc':'Электр техникасы саласында үлкен тәжірибесі бар жоғары білікті мамандар тобы.',
      'contact.title':'Бізге жазыңыз',
      'contact.name':'Аты-жөні',
      'contact.company':'Компания атауы',
      'contact.phone':'Телефон нөмірі',
      'contact.email':'Электрондық пошта',
      'contact.message':'Хабарлама',
      'contact.submit':'Жіберу',
      'contact.info_title':'Байланыс ақпараты',
      'contact.address': '📍 Мекенжай: Орынғали Смағұлов көшесі, 13',
  
      'services.hero.title': 'Қызметтер мен өнімдер',
      'services.hero.subtitle': 'Электрқозғалтқыштарды кешенді жөндеу және қызмет көрсету, сапа кепілдігімен',
      'services.hero.button': 'Есептеу сұрау',
      'services.services.title': 'Біздің қызметтер',
      'services.service1.title': 'Электр қозғалтқыштарын жөндеу',
      'services.service1.desc': 'Кез келген күрделіліктегі асинхронды және синхронды қозғалтқыштарды ағымдағы және күрделі жөндеу.',
      'services.service1.item1': 'Подшипник тораптарын ауыстыру',
      'services.service1.item2': 'Корпус пен білікті жөндеу',
      'services.service1.item3': 'Геометрияны қалпына келтіру',
      'services.service2.title': 'Орамаларды қайта орау',
      'services.service2.desc': 'Сапалы материалдарды қолданып статор мен роторды кәсіби қайта орау.',
      'services.service2.item1': 'Ораманы толық ауыстыру',
      'services.service2.item2': 'Оқшаулауды сіңдіру (пропитка)',
      'services.service2.item3': 'Кедергіні бақылау',
      'services.service3.title': 'Диагностика және сынақ',
      'services.service3.desc': 'Заманауи өлшеу жабдықтарын қолдана отырып кешенді диагностика.',
      'services.service3.item1': 'Вибродиагностика',
      'services.service3.item2': 'Орамаралық сынақ',
      'services.service3.item3': 'Оқшаулаудың кедергісін өлшеу',
      'services.service4.title': 'Техникалық қызмет көрсету',
      'services.service4.desc': 'Апатты жағдайлардың алдын алу және қызмет мерзімін ұзарту үшін тұрақты ТО.',
      'services.service4.item1': 'Жоспарлы тексерістер',
      'services.service4.item2': 'Подшипниктерді майлау',
      'services.service4.item3': 'Бекітпелерді тексеру',
      'services.service5.title': 'Роторды теңгеру',
      'services.service5.desc': 'Діріл мен шуды жоюға арналған дәл динамикалық теңгеру.',
      'services.service5.item1': 'Стендте теңгеру',
      'services.service5.item2': 'Соғуды (биение) жою',
      'services.service5.item3': 'Біліктерді центрлеу',
      'services.service6.title': 'Жаңғырту және апгрейд',
      'services.service6.desc': 'Қозғалтқыш сипаттамаларын жақсарту және заманауи технологияларды енгізу.',
      'services.service6.item1': 'Датчиктер орнату',
      'services.service6.item2': 'Оқшаулау класын көтеру',
      'services.service6.item3': 'Салқындатуды оңтайландыру',
  
      'services.products.title': 'Өнімдер',
      'services.product1.title': 'Подшипниктер және ремкомплекттер',
      'services.product1.desc': 'Барлық қозғалтқыш түрлеріне арналған жетекші өндірушілердің сапалы подшипниктері.',
      'services.product1.item1': 'Шарикті подшипниктер',
      'services.product1.item2': 'Роликті подшипниктер',
      'services.product1.item3': 'Сальниктер мен тығыздағыштар',
      'services.product2.title': 'Оқшаулағыш материалдар және лактар',
      'services.product2.desc': 'Орамаларды сенімді қорғауға арналған F/H классты жылуға төзімді оқшаулағыштар.',
      'services.product2.item1': 'Слюдопласт оқшаулауы',
      'services.product2.item2': 'Сіңдіру лактары',
      'services.product2.item3': 'Электртехникалық картон',
      'services.product3.title': 'Қосалқы бөлшектер және жинақтаушылар',
      'services.product3.desc': 'Электр қозғалтқыштарына арналған түпнұсқа және үйлесімді бөлшектердің кең таңдауы.',
      'services.product3.item1': 'Салқындату желдеткіштері',
      'services.product3.item2': 'Клеммалық қораптар',
      'services.product3.item3': 'Щетка ұстағыштар',
  
      'services.specs.title': 'Техникалық мүмкіндіктер',
      'services.specs.note': '* Шамамен мәндер — нақты жобаға қарай нақтыланады',
      'services.specs.power.value': '0.37–500 кВт',
      'services.specs.power.label': 'Қуат',
      'services.specs.voltage.value': '6.6 кВ дейін',
      'services.specs.voltage.label': 'Кернеу',
      'services.specs.insulation.value': 'F / H',
      'services.specs.insulation.label': 'Оқшаулау класы',
      'services.specs.balancing.value': 'ISO 1940-1',
      'services.specs.balancing.label': 'Теңгеру',
      'services.specs.testing.value': '5 түрі',
      'services.specs.testing.label': 'Сынақтар',
      'services.specs.warranty.value': '1 айға дейін',
      'services.specs.warranty.label': 'Кепілдік',
  
      'services.why.title': 'Неліктен EMS таңдайды',
      'services.why1.title': 'Оңтайлы мерзімдер',
      'services.why1.desc': 'Жұмысты нақты жоспарлау және келісілген мерзімдерді сақтау.',
      'services.why2.title': 'Сапаны бақылау',
      'services.why2.desc': 'Әр кезеңде көпсатылы тексеріс және қорытынды сынақтар.',
      'services.why3.title': 'Шарт және құжаттар',
      'services.why3.desc': 'Ресми рәсімдеу, құжаттардың толық пакеті, орындалған жұмыс актілері.',
      'services.why4.title': 'Кепілдік қызмет',
      'services.why4.desc': 'Барлық жұмыстарға кепілдік және кепілдіктен кейінгі қызмет көрсету мүмкіндігі.',

      'modal.title': 'EMS-пен байланысу',
      'modal.subtitle': 'Қолайлы тәсілді таңдаңыз',
      'modal.call': '📞 Қоңырау шалу: +7 (775) 552-44-14',
      'modal.whatsapp': '💬 WhatsApp',

      'training.hero.title': 'Оқыту және материалдар',
      'training.hero.subtitle': 'Электрқозғалтқыштарды жөндеу бойынша кәсіби оқу материалдары мен бейненұсқаулықтар',
      'training.hero.button': 'Сұрағыңызды қойыңыз',

      'training.videos.title': 'Оқыту бейнелері',
      'training.videos.v1.title': 'Электрқозғалтқыш диагностикасы',
      'training.videos.v2.title': 'Статор орамдарын қайта орау',
      'training.videos.v3.title': 'Теңгеру және центрлеу',

      'training.materials.m1.title': 'Техникалық құжаттама',
      'training.materials.m1.desc': 'Әртүрлі электрқозғалтқыш түрлеріне арналған нұсқаулықтар, қосу сұлбалары және сипаттамалар',
      'training.materials.m2.title': 'Әдістемелік құралдар',
      'training.materials.m2.desc': 'Суреттері бар жөндеу, қайта орау және диагностика бойынша қадамдық нұсқаулар',
      'training.materials.m3.title': 'Стандарттар мен нормалар',
      'training.materials.m3.desc': 'Электр жабдықтары мен қауіпсіздікке арналған ГОСТ, ISO және басқа нормативтер',

      'about.hero.title': 'Біз туралы',
      'about.hero.subtitle': '2019 жылдан бері электрқозғалтқыштарды кәсіби жөндеу және қызмет көрсету',

      'about.stats.years': 'жыл тәжірибе',
      'about.stats.motors': 'қозғалтқыш / жыл',
      'about.stats.warranty': 'ай кепілдік',

      'about.why.title': 'Неліктен бізді таңдайды',
      'about.why.card1.title': 'Кәсібилік',
      'about.why.card1.desc': 'Тәжірибелі мамандар және тұрақты біліктілікті арттыру',
      'about.why.card2.title': 'Заманауи жабдық',
      'about.why.card2.desc': 'Қазіргі диагностикалық және жөндеу жабдықтарын қолданамыз',
      'about.why.card3.title': 'Сапа кепілдігі',
      'about.why.card3.desc': 'Барлық жұмысқа ресми кепілдік және толық құжаттама',
      'about.why.card4.title': 'Мерзімді сақтау',
      'about.why.card4.desc': 'Жұмысты нақты жоспарлап, келісілген мерзімде тапсырамыз',

      'about.process.title': 'Қалай жұмыс істейміз',
      'about.process.step1.title': 'Өтінімді қабылдау',
      'about.process.step1.desc': 'Телефон арқылы немесе сайттан хабарласып, мәселені сипаттайсыз',
      'about.process.step2.title': 'Диагностика',
      'about.process.step2.desc': 'Кәсіби жабдықпен кешенді диагностика жүргіземіз',
      'about.process.step3.title': 'Келісу',
      'about.process.step3.desc': 'Смета жасап, жұмыс көлемі мен мерзімін келісеміз, шарт жасаймыз',
      'about.process.step4.title': 'Жөндеу',
      'about.process.step4.desc': 'Сапалы материалдар мен бөлшектерді қолданып жөндеу жүргіземіз',
      'about.process.step5.title': 'Тапсыру',
      'about.process.step5.desc': 'Қорытынды сынақ, құжаттау және тапсырыс берушіге тапсыру',

      'about.faq.title': 'Жиі қойылатын сұрақтар',
      'about.faq.q1.question': 'Диагностика қанша уақыт алады?',
      'about.faq.q1.answer': 'Алдын ала диагностика қозғалтқыш түрі мен қуатына байланысты 1–3 сағат алады. Нәтиже бірден беріледі.',
      'about.faq.q2.question': 'Кепілдік бересіздер ме?',
      'about.faq.q2.answer': 'Иә. Барлық жұмысқа 1 айға дейін ресми кепілдік береміз. Ол шартта көрсетіледі.',
      'about.faq.q3.question': 'Қандай қозғалтқыштарды жөндейсіздер?',
      'about.faq.q3.answer': 'Асинхронды, синхронды, тұрақты ток қозғалтқыштары және басқа да түрлерімен жұмыс істейміз.',
      'about.faq.q4.question': 'Алдын ала бағалау үшін фото/видео керек пе?',
      'about.faq.q4.answer': 'Шильдик (мәлімет тақтайшасы) және жалпы көрініс фотосы құн мен мерзімді дәлірек айтуға көмектеседі.',
      'about.faq.q5.question': 'Жөндеу құнын қалай білемін?',
      'about.faq.q5.answer': 'Нақты құн диагностикадан кейін белгілі болады. Алдын ала бағалау — телефон арқылы немесе фото/мәлімет бойынша.',
      'about.faq.q6.question': 'Жөндеуді қанша уақытта бітіресіздер?',
      'about.faq.q6.answer': 'Күрделілігіне байланысты: жеңіл жөндеу 3–5 күн, күрделі 7–14 күн, қайта орау 10–21 күн. Жедел жөндеу келісім бойынша.',

      'about.cta.title': 'Жұмысты бастаймыз ба?',
      'about.cta.subtitle': 'Кеңес және алдын ала есептеу үшін бізге жазыңыз',
      'about.cta.button': 'Байланысу',
    }
  };
  
  function applyTranslations(lang) {
    const texts = document.querySelectorAll('[data-i18n]');
    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
  
    texts.forEach(el => {
      const key = el.getAttribute('data-i18n');
      const translated = translations[lang]?.[key];
      if (translated) el.textContent = translated;
    });
  
    placeholders.forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      const translated = translations[lang]?.[key];
      if (translated) el.setAttribute('placeholder', translated);
    });
  
    const currentLangEl = document.getElementById('currentLang');
    if (currentLangEl) currentLangEl.textContent = lang.toUpperCase();
  
    const langDropdown = document.getElementById('langDropdown');
    if (langDropdown) langDropdown.classList.remove('active');
  
    document.dispatchEvent(new CustomEvent('langChanged', { detail: { lang } }));
  }

  function setupLanguageDropdown() {
    const langBtn = document.getElementById("langBtn");
    const langDropdown = document.getElementById("langDropdown");
  
    if (langBtn && langDropdown) {
      langBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        langDropdown.classList.toggle("active");
      });
  
      document.addEventListener("click", (event) => {
        if (!langBtn.contains(event.target) && !langDropdown.contains(event.target)) {
          langDropdown.classList.remove("active");
        }
      });
    }
  
    document.querySelectorAll('.lang-option').forEach(option => {
      option.addEventListener('click', () => {
        const selectedLang = option.getAttribute('data-lang') || 'ru';
        localStorage.setItem('lang', selectedLang);
        applyTranslations(selectedLang);
      });
    });
  
    const savedLang = localStorage.getItem('lang') || 'ru';
    applyTranslations(savedLang);
  }
  
  document.addEventListener("DOMContentLoaded", setupLanguageDropdown);
  